export enum CampoFormularioTipo {
  TEXTO_CURTO = 'TEXTO_CURTO',
  TEXTO_LONGO = 'TEXTO_LONGO',
  NUMERO_INTEIRO = 'NUMERO_INTEIRO',
  MOEDA = 'MOEDA',
  DATA = 'DATA',
  ARQUIVO = 'ARQUIVO',
  SELECAO = 'SELECAO',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
  TOGGLE = 'TOGGLE',
}
